### ISSUE TITLE
How do i use this theme

### ISSUE THREAD

**Issue by NFS002** [benradford/Slate-and-Simple-Jekyll-Theme#4]
Hi,

Sorry, I am a complete newbie. How do I install/use this theme in my own blog ?

**Comment by benradford** [comment]
Hi Noah - this theme uses Jekyll. There are several tutorials about using Jekyll online:

- http://jekyllbootstrap.com/lessons/jekyll-introduction.html
- https://jekyllrb.com/docs/
- https://jekyllrb.com/tutorials/home/
- https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages

Jekyll is for building static webpages (no scripts or databases running on the server). It is also built for making websites very quickly, simply, and without having to duplicate a lot of code. The idea is that there are theme and layout files to define the form and function of your website and then there are your content files (pages, blog posts, images). Content can be written very simply using markdown or standard HTML. 

You compile the website on your own computer using the Jekyll software. Once it is compiled, you can upload the static webpages that are generated to your web host. Github pages offers free hosting of Jekyll pages (the last link in the list above). If you use Github as your host, you do not even need to compile the website on your computer - Github will compile it for you. 

To get started, you can clone the slate-and-simple-jekyll-theme repository and start editing the files in /_posts/. You can add or delete posts (.md files) and the website will be updated next time it is compiled. 

Good luck!

**Comment by NFS002** [comment]
thanks very much :)
